# For-løkker, sekvenser, range-objekter - intro
(Denne noteboka viser ikke nyttige eksempler med for-løkker men fokuserer på å få fram hvordan de virker)

For-løkker går gjennom sekvenser av elementer:

In [1]:
for tall in [3,4,11,7,9]:
    print(tall)

3
4
11
7
9


Som vi ser, kjørte for-løkka ovenfor 5 ganger, hvor
- tall fikk verdi 3 (i første runde), så 4, så 11, så 7, så 9

Dvs., generell syntaks er 

_for \<løkkevariabel\> in \<sekvens\>:_
- _kodelinjer på innrykk_

De kodelinjene som står på innrykk under for-setninga, tilhører løkka

Kodelinjer som er på margen utenfor igjen, tilhører ikke løkka.

In [2]:
print('før')
for i in []:
    print('inni')
    print('og')
print('etter')

før
etter


Med en helt tom sekvens (f.eks. tom liste, som over) kjøres ikke løkka i det hele tatt.

Her printet vi før, etter fordi de kommer foran og bak løkka
- mens inni, og ble ikke printet fordi de var inni løkka

I koden nedenfor blir "og" også printet fordi den er rykket ut på forrige marg:

In [3]:
print('før')
for i in []:
    print('inni')
print('og')
print('etter')

før
og
etter


Med ei liste på ett element, kjøres løkka en gang (ordet inni kommer en gang): 

In [4]:
print('før')
for i in [3]:
    print('inni')
print('og')
print('etter')

før
inni
og
etter


Med to element, blir det to ganger (osv.)

In [5]:
print('før')
for i in [3, 3]:
    print('inni')
print('og')
print('etter')

før
inni
inni
og
etter


For å vise på en effektiv måte hvordan for-løkke virker med ulike slags sekvenser, lager vi nå en liten funksjon som returnerer en streng. Strengen begynner alltid med * (legges inn før løkka) og slutter alltid med + (legges til etter løkka), men alt som kommer mellom disse to symbolene forårsakes av koden i løkka:

In [13]:
import numpy as np

def lag_streng(sekvens):
    streng = '*'
    for element in sekvens:
        streng += str(element)
        streng += ' ; '
    streng += '+'
    return streng

print(lag_streng([4,5,2]))
print(lag_streng(np.array([3.2, 3.4, 2.1])))

*4 ; 5 ; 2 ; +
*3.2 ; 3.4 ; 2.1 ; +


Antall semikolon i strengen viser hvor mange ganger løkka har kjørt. 

I tilfellet over 3 ganger:
- fordi sekvensen som ble brukt i første kjøring var ei liste med 3 element
- og tilsvarende i andre kjøring, et numpy-array med tre element

In [11]:
print(lag_streng(np.array([])))

*+


Som vi ser over: et helt tomt array gjør at løkka ikke kjører i det hele tatt. (samme ville vært tilfelle for ei tom liste)

Strenger er også sekvenser, og kan utmerket godt gis inn til for-løkker:

In [14]:
print(lag_streng('ITGK'))
print(lag_streng('Python'))
print(lag_streng(''))

*I ; T ; G ; K ; +
*P ; y ; t ; h ; o ; n ; +
*+


Her ser vi på tilsvarende måte at
- en helt tom streng vil gjøre at løkka ikke kjører i det hele tatt. 

Hvis strengen har et innhold, får løkkevariabelen
- først verdi som det fremste tegnet, 
- så verdi som det neste tegnet, osv., 
- inntil alle tegnene er tatt.

## range-objekter
Noen ganger trenger vi enten
- bare å kjøre ei løkke et visst antall ganger
    - uten at det er knyttet til verdier i f.eks. ei liste eller et array
- eller å kjøre løkka gjennom en regulær tallsekvens

Da er det gjerne enklere å bruke range-objekter enn å sette opp lister med tallene.

Et range-objekt kan opprettes ved å kalle funksjonen __range( )__ fra Pythons standardbibliotek. 

Gjentar funksjonen vår og viser hva den gjør med et par range-objekter som sekvens:

In [15]:
def lag_streng(sekvens):
    streng = '*'
    for element in sekvens:
        streng += str(element)
        streng += ' ; '
    streng += '+'
    return streng

print(lag_streng(range(5)))
print(lag_streng(range(2,6)))
print(lag_streng(range(1,10,3)))
print(lag_streng(range(20,-1,-4)))

*0 ; 1 ; 2 ; 3 ; 4 ; +
*2 ; 3 ; 4 ; 5 ; +
*1 ; 4 ; 7 ; +
*20 ; 16 ; 12 ; 8 ; 4 ; 0 ; +


Som vi ser av kjøring av cella over:
- range(5) gjør at løkka kjører 5 ganger, med tallsekvensen 0,1,2,3,4
    - dvs., når range gis kun ett argument, er dette tallet _til_-verdi
        - som __ikke__ er "til og med", siden tallet 5 ikke er med i sekvensen
    - default startverdi for range( ) er 0
    - default stegverdi er 1, dvs. for hvert tall i sekvensen øker verdien med 1
- range(2,6) gir sekvensen 2, 3, 4, 5
    - med to argument blir første startverdi, andre blir til-verdi
    - stegverdi er fortsatt default, +1
- hvis vi ønsker en annen stegverdi enn +1, må vi gi inn et tredje argument til range()
    - range(1, 10, 3) gir dermed sekvensen 1, 4, 7
        - og fremdeles ikke 10, siden til-verdi ikke er med
    - range(20, -1, -4) viser at vi også kan telle baklengs: 20, 16, 12, 8, 4, 0
        - her blir stegverdi -4, dvs. trekker fra 4 for hver runde
        - siste tall i sekvensen blir 0, siden til-verdi var satt til -1 som er mindre enn 0
    

Et lite eksempel på en funksjon som bruker range() bare til å bestemme antall ganger ei løkke skal kjøre:

In [16]:
def stabil_latter(antall):
    streng = ''
    for i in range(antall):
        streng += 'ha'
    return streng

print(stabil_latter(0))
print(stabil_latter(4))


hahahaha


Som vi ser, med 0 satt inn for antall, blir ikke løkka kjørt i det hele tatt, og vi printer bare ei tom linje. Med 4 satt inn for antall får vi 4x 'ha'. I dette eksemplet brukes løkkevariabelen kun til å styre antall ganger løkka skal kjøre, tallene i sekvensen 0,1,2,3 brukes ikke til noe mer inni løkka. Funksjonen kunne ha vært laget enklere uten løkke, bare ved

In [19]:
def stabil_latter(antall):
    return 'ha' * antall

print(stabil_latter(4))

hahahaha


I det neste eksemplet bruker vi imidlertid verdien til __i__ fra range-sekvensen også til beregninger inni løkka, da er det vanskelig å få til samme funksjon uten løkke:

In [23]:
def stigende_latter(antall):
    streng = ''
    for i in range(antall):
        streng += 'h' + 'a' * (i+1)
    return streng

print(stigende_latter(4))

hahaahaaahaaaa


## numpy.arange( ), numpy.linspace( ), numpy.zeros( ), numpy.ones( )

Hvis vi gjør beregninger i numpy, er det ofte hensiktsmessig å få til tallsekvenser som numpy-arrays heller enn range-objekter. Blant annet kan følgende funksjoner være av interesse:

- numpy.arange() virker på samme måte som range()
    - argumenter inn er startverdi, sluttverdi, stegverdi
    - med default 0 for start, 1 for steg akkurat som range()
    - i motsetning til range, __kan__ vi også ha flyttall som stegverdier
    
Eksemplet under lager et array med verdier fra og med 1, til (men ikke med) 5, med stegverdi 0.2

In [24]:
import numpy as np
np.arange(1, 5, 0.2)

array([1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4, 2.6, 2.8, 3. , 3.2, 3.4,
       3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8])

I tilfeller med stegverdier som ikke er hele tall, kan det ofte være vel så hensiktsmessig å bruke funksjonen numpy.linspace(). Den gir
- verdier fra og med en startverdi
- til og med en sluttverdi
- med totalt antall verdier i sekvensen som tredje argument

Eksemplet under gir den samme sekvensen som vi lagde med arange over:

In [28]:
import numpy as np
np.linspace(1, 4.8, 20)

array([1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4, 2.6, 2.8, 3. , 3.2, 3.4,
       3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8])

Av og til kan vi ønske et helt array med bare nuller, eller bare enere, f.eks. som startverdier som vi senere skal oppdatere underveis i ei løkke. Dette kan oppnås med funksjonene numpy.zeros() og numpy.ones(). Eksempelkallene under gir ett array med 10 nuller, og ett array med 5 enere.

In [30]:
import numpy as np
np.zeros(10), np.ones(5)

(array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]), array([1., 1., 1., 1., 1.]))